name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '22'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build static files
        run: npm run build

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{vars.FTP_SERVER}}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: out/
          server-dir: ${{vars.FTP_SERVER_DIR}}
